services:
  waha:
    image: devlikeapro/waha:chrome
    container_name: waha
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      WAHA_API_KEY: mywahakey
      WAHA_DASHBOARD_ENABLED: "false"
      WAHA_DASHBOARD_USERNAME: admin
      WAHA_DASHBOARD_PASSWORD: admin123
      WHATSAPP_DEFAULT_ENGINE: WEBJS
      WAHA_PRINT_QR: "false"
      TZ: Africa/Cairo
      WAHA_RUN_XVFB: "false"
      WAHA_WEBJS_PUPPETEER_ARGS: --no-sandbox --disable-setuid-sandbox --disable-blink-features=AutomationControlled --disable-infobars --window-position=0,0 --ignore-certifcate-errors --ignore-certifcate-errors-spki-list --disable-default-apps --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
      WHATSAPP_WEBHOOK_URL: "http://host.docker.internal:3001/api/webhook"
      WHATSAPP_WEBHOOK_EVENTS: "message,message.any,session.status"
    volumes:
      - ./.waha/.sessions:/app/.sessions
